### ISSUE TITLE
Chandigarh LR workflow software issue:

### ISSUE THREAD

**Issue by Sagar8903** [Sagar8903/CH-LR-DMS-Work-Flow-Software-Issue-register#1]
Please note all issues here :

**Comment by Sagar8903** [comment]
![IMG-20240214-WA0001.jpg](https://github.com/Sagar8903/CH-LR-DMS-Work-Flow-Software-Issue-register/assets/159136551/e3a71fc0-cef5-458c-927a-cdc436084763)

**Comment by Sagar8903** [comment]
[]() trying

**Comment by Sagar8903** [comment]
- [ ] https://github.com/Sagar8903/CH-LR-DMS-Work-Flow-Software-Issue-register/assets/159136551/876d09d0-1f57-45c9-829a-76b7654cb04f

**Comment by Sagar8903** [comment]
[https://www.youtube.com/watch?v=Qqqt671r_7M](url)

**Comment by Sagar8903** [comment]
[https://www.facebook.com/watch/?ref=tab](url)

**Comment by Shashikumar9650** [comment]
- [ ] hdjaajsdh

**Comment by Sagar8903** [comment]
@Shashikumar9650 Please confirm regarding the Export Issue ... If you are able export without problem please share more batches as we would require them for Upload in the DMS.

**Comment by Shashikumar9650** [comment]
Dear sir,

Ch-lr software work problem paf generated and csb not working properly.

**Comment by Sagar8903** [comment]
Issue regarding export. After audit acceptance the batch is not showing in the Export option. @sumitntpl123 


Uploading WhatsApp Video 2024-02-21 at 3.36.34 PM (1).mp4…

**Comment by Sagar8903** [comment]
> Issue regarding export. After audit acceptance the batch is not showing in the Export option. @sumitntpl123
> 
> Uploading WhatsApp Video 2024-02-21 at 3.36.34 PM (1).mp4…

**Comment by Sagar8903** [comment]
@Shashikumar9650 Please provide 10 exported batches. (both CSV and PDF files of a batch).
